const i18nObj = {
    'en': {
      'skills': 'Skills',
      'portfolio': 'Portfolio',
      'video': 'Video',
      'price': 'Price',
      'contacts': 'Contacts',
      'en': 'EN',
      'ru': 'RU',
      'hero-title': 'Alexa Rise',
      'hero-text': 'Save sincere emotions, romantic feelings and happy moments of life together with professional photographer Alexa Rise',
      'hero-button': 'Hire me',
      'skill-photo-subtitle': 'Digital photography',
      'skill-photo-text': 'High-quality photos in the studio and on the nature',
      'skill-video-subtitle': 'Video shooting',
      'skill-video-text': 'Capture your moments so that they always stay with you',
      'skill-retouch-subtitle': 'Rotouch',
      'skill-retouch-text': 'I strive to make photography surpass reality',
      'skill-audio-subtitle': 'Audio',
      'skill-audio-text': 'Professional sounds recording for video, advertising, portfolio',
      'winter': 'Winter',
      'spring': 'Spring',
      'summer': 'Summer',
      'autumn': 'Autumn',
      'price-subtitle-standart': 'Standart',
      'price-subtitle-premium': 'Premium',
      'price-subtitle-gold': 'Gold',
      'price-description-1-span-1': 'One location',
      'price-description-1-span-2': '120 photos in color',
      'price-description-1-span-3': '12 photos in retouch',
      'price-description-1-span-4': 'Readiness 2-3 weeks',
      'price-description-1-span-5': 'Make up, visage',
      'price-description-2-span-1': 'One or two locations',
      'price-description-2-span-2': '200 photos in color',
      'price-description-2-span-3': '20 photos in retouch',
      'price-description-2-span-4': 'Readiness 1-2 weeks',
      'price-description-2-span-5': 'Make up, visage',
      'price-description-3-span-1': 'Three locations or more',
      'price-description-3-span-2': '300 photos in color',
      'price-description-3-span-3': '50 photos in retouch',
      'price-description-3-span-4': 'Readiness 1 week',
      'price-description-3-span-5': 'Make up, visage, hairstyle',
      'order': 'Order shooting',
      'contact-me': 'Contact me',
      'email': 'E-mail',
      'phone': 'Phone',
      'message': 'Message',
      'send-message': 'Send message'
    },
    'ru': {
      'skills': 'Навыки',
      'portfolio': 'Портфолио',
      'video': 'Видео',
      'price': 'Цены',
      'contacts': 'Контакты',
      'en': 'АНГЛ',
      'ru': 'РУС',
      'hero-title': 'Алекса Райс',
      'hero-text': 'Сохраните искренние эмоции, романтические переживания и счастливые моменты жизни вместе с профессиональным фотографом Алексой Райс',
      'hero-button': 'Пригласить',
      'skill-photo-subtitle': 'Фотография',
      'skill-photo-text': 'Высококачественные фото в студии и на природе',
      'skill-video-subtitle': 'Видеосъемка',
      'skill-video-text': 'Запечатлите лучшие моменты, чтобы они всегда оставались с вами',
      'skill-retouch-subtitle': 'Ретушь',
      'skill-retouch-text': 'Я стремлюсь к тому, чтобы фотография превосходила реальность',
      'skill-audio-subtitle': 'Звук',
      'skill-audio-text': 'Профессиональная запись звука для видео, рекламы, портфолио',
      'winter': 'Зима',
      'spring': 'Весна',
      'summer': 'Лето',
      'autumn': 'Осень',
      'price-subtitle-standart': 'Стандарт',
      'price-subtitle-premium': 'Премиум',
      'price-subtitle-gold': 'Голд',
      'price-description-1-span-1': 'Одна локация',
      'price-description-1-span-2': '120 цветных фото',
      'price-description-1-span-3': '12 отретушированных фото',
      'price-description-1-span-4': 'Готовность через 2-3 недели',
      'price-description-1-span-5': 'Макияж, визаж',
      'price-description-2-span-1': 'Одна-две локации',
      'price-description-2-span-2': '200 цветных фото',
      'price-description-2-span-3': '20 отретушированных фото',
      'price-description-2-span-4': 'Готовность через 1-2 недели',
      'price-description-2-span-5': 'Макияж, визаж',
      'price-description-3-span-1': 'Три локации и больше',
      'price-description-3-span-2': '300 цветных фото',
      'price-description-3-span-3': '50 отретушированных фото',
      'price-description-3-span-4': 'Готовность через 1 неделю',
      'price-description-3-span-5': 'Макияж, визаж, прическа',
      'order': 'Заказать съемку',
      'contact-me': 'Свяжитесь со мной',
      'email': 'Почта',
      'phone': 'Телефон',
      'message': 'Сообщение',
      'send-message': 'Отправить'
    }
  }
  export default i18nObj;